### ISSUE TITLE
组播地址问题

### ISSUE THREAD

**Issue by terry386** [babylife/China-Unicom-ShangHai-IPTV-list#1]
上海联通宽带，开通了IPTV，用超级直播app导入组播地址，无法播放，请教下有解决办法么，谢谢！
另外超级直播使用无参数版本的时移地址，可以正常播放，就是切换频道有点卡，是因为8000kbps码率太高的原因么？

**Comment by babylife** [comment]
组播地址，需要IGMP snooping的路由器支持，如果不支持的话，组播是没有办法使用的。 
时移地址测试可以使用PC对比测试， 我家里的情况是有的电视也有支持问题，目前测试下来，组播是最快的，推荐使用梅林固件。希望可以帮到你

**Comment by babylife** [comment]
抱歉，推荐使用时移地址，组播地址不知道如何提取
