### ISSUE TITLE
在fancyss项目没有开启lssues，只能在这寻求帮助了！

### ISSUE THREAD

**Issue by sszling** [babylife/China-Unicom-ShangHai-IPTV-list#2]
babylife大大，K3的梅林固件已经可以升级到384版本了，我安装了fancyss_arm384的1.0.4版本后发现没有支持Trojan，能否麻烦你抽空编译个能支持Trojan的版本，万分感谢！！

**Comment by babylife** [comment]
384支持trojan的版本在Merlin clash的电报群有，可以从那里下载，属于魔改 ，GITHUB上作者没有放上来，如果找不到，请留言给我
