### ISSUE TITLE
麻烦大神更新一下频道列表

### ISSUE THREAD

**Issue by revy2333** [babylife/China-Unicom-ShangHai-IPTV-list#3]
最近频道更新了 cctv2也有高清了 麻烦大神重新抓包下

**Comment by babylife** [comment]
好的

**Comment by babylife** [comment]
CCTV-1HD,http://20.254.1.9/PLTV/88888888/224/3221225703/10000100000000060000000000035351_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlPNfmvBh0ZA%2FQDyl%2BElHmTxA%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F111128%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-2HD,http://20.254.1.9/PLTV/88888888/224/3221225881/10000100000000060000000001558309_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTqn3jcwDVh%2BrOc4EZracVX0Q%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F5000036%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-3HD,http://20.254.1.9/PLTV/88888888/224/3221225861/10000100000000060000000001067918_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlP6fiM9VxPehNgiVHXarlRWA%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F1369028%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-4HD,http://20.254.1.9/PLTV/88888888/224/3221225882/10000100000000060000000001558308_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTqGRafYUVNEEKzw47vvGnvig%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F5000037%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-5HD,http://20.254.1.9/PLTV/88888888/224/3221225862/10000100000000060000000001067915_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlP6lchWtfyZAJtuVaynbLEeQ%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F1369029%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-6HD,http://20.254.1.9/PLTV/88888888/224/3221225863/10000100000000060000000001067916_0.smil/index.m3u8?rrsip=20.254.1.9&fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlPg7BIkvKwVz91jwTvI9VH1g%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F1369030%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-7HD,http://20.254.1.9/PLTV/88888888/224/3221225887/10000100000000060000000001558688_0.smil/index.m3u8?rrsip=20.254.1.9&fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTq9rS83KO2XdI0VE8WMBpclw%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F5000038%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-8HD,http://20.254.1.9/PLTV/88888888/224/3221225864/10000100000000060000000001067917_0.smil/index.m3u8?rrsip=20.254.1.9&fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlPMswXRzJfkgaRUzA838bgGw%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F1369033%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-9HD,http://20.254.1.9/PLTV/88888888/224/3221225888/10000100000000060000000001558690_0.smil/index.m3u8?rrsip=20.254.1.9&fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTqgLmZ0pyecC3DicLWlJCmSA%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F5000039%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-10HD,http://20.254.1.9/PLTV/88888888/224/3221225889/10000100000000060000000001558694_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTq1TAFxGHRBwOO7dh8AUFu0A%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F3949784%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-11,http://20.254.1.9/PLTV/88888888/224/3221225655/10000100000000060000000000012465_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=Uqeq%2Boy1dBELxCuFvRpa8czSquKOOo%2FFQ5zRdldos3PBFGcZsESCluF%2FGBAW8LefJaKHbXhBoFItRV%2F7vFw%2BjITKf0d6isZF3YWGVGkjqKV%2BW7Bhzc0iaHEWEnLae%2FlPddrpKreEGCpvMcF%2FsXQ%2FTA%3D%3D%3A20200106134815%2CIPTV00193335%2C112.64.29.18%2C20200106134815%2CUmai%3ACHAN%2F1356%40BESTV.SMG.SMG%2C389B98319D02CA30AD44A33B2CA755AF%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND
CCTV-12HD,http://20.254.1.9/PLTV/88888888/224/3221225890/10000100000000060000000001558689_0.smil/index.m3u8?fmt=ts2hls&servicetype=2&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&GuardEncType=2&accountinfo=1yfx5mfy9e%2B5KXzoeyCHMm2jwcqfaFSznY7JZFnx8RQyskn%2B7ZjZEVibA%2FpNOVxc1m1l74f0hINk64BJ%2BTpeSoTKf0d6isZF3YWGVGkjqKXKaAyqF%2BDac1OsiyKTndTqoTp3Itk3WNDEFWRMGtktoQ%3D%3D%3A20210314155237%2CIPTV00193335%2C58.247.70.69%2C20210314155237%2CUmai%3ACHAN%2F5000040%40BESTV.SMG.SMG%2C116133D039A49CE693B8902B5503B668%2C-1%2C1%2C1%2C%2C%2C7%2C%2C%2C%2C4%2CEND

**Comment by babylife** [comment]
先提取出来给你，下次统一整理，时间久了都忘记之前是怎么一次性整理的了
