### ISSUE TITLE
貌似不能用了，求大佬更新

### ISSUE THREAD

**Issue by Joooosannnnnn** [babylife/China-Unicom-ShangHai-IPTV-list#4]
上海教育网测试了下都打不开

**Comment by babylife** [comment]
今天发现上海联通是不行了，找时间更新下

**Comment by Joooosannnnnn** [comment]
同时请教一下大佬上海联通IPTV组播使用教程，光猫和路由器的设置。光猫和路由器单线连接的，路由器是openwrt

**Comment by babylife** [comment]
> 同时请教一下大佬上海联通IPTV组播使用教程，光猫和路由器的设置。光猫和路由器单线连接的，路由器是openwrt

组播只研究了上海电信，联通的非组播地址原来也可以用，不知道是不是现在不行了。月底研究下

**Comment by babylife** [comment]
联通还是正常可以使用
