### ISSUE TITLE
上海联通关了组播？

### ISSUE THREAD

**Issue by colinhd8** [babylife/China-Unicom-ShangHai-IPTV-list#5]
请教下，上海联通是不是关了组播了？原来用得好好的，在路由器，光猫，交换机都没改配置的情况下，忽然看不了组播了。
通过抓包，发现机顶盒在看直播时，也已经不是通过组播来观看了。

又或者是联通把组播vlan改了？

**Comment by babylife** [comment]
好像是的 明天测试下

**Comment by colinhd8** [comment]
谢谢，等你测试。我现在都是通过类似这样的地址观看了：rtsp://20.254.1.9/PLTV/88888888/224/3221225855/10000100000000060000000001175042_0.smil

以前都是组播地址。

**Comment by mhqschen** [comment]
想问下组播是确定关了么？

**Comment by colinhd8** [comment]
我认为是的。从抓包来看，机顶盒也不用组播了。
